const MINT = "6ZhVVH2KwbiVg6HJjrPg2YC5SWomBFA5qGmz57pknMpz";
const reserves = [
  ["Liquidity", "500M planned", "8zMNiAh2uH1MoKh9eRjewSrgRjU4WQAYVV2u4SKSiRfU"],
  ["Ecosystem", "200M planned", "44Ha31Tj911xtFcNv5e4RTD7f3NxhULtcUygBJm8on1g"],
  ["Community", "150M planned", "BFYWFeqf8uJ4BvD6dfySCkdMVdtDPvxFe5hmSzuCCbhg"],
  ["Treasury", "75M planned", "6gkNMy3342qVUKSatW27zUAK22ops5Fu7G5J148MQZK6"],
  ["Team", "75M planned", "CvASopxtFapEhJ8r75UcHiisPVCfxv5ApGAqbwNagXmw"],
] as const;

export default function TransparencyPage() {
  return <main className="min-h-screen bg-[#080a0d] text-[#f7f1e5]"><div className="mx-auto max-w-5xl px-5 py-12 sm:px-8 sm:py-16">
    <a href="/" className="text-xs font-bold text-[#e9b949]">← MALTY</a>
    <p className="mt-10 text-[10px] font-black tracking-[.24em] text-[#e9b949]">TRANSPARENCY CENTER</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em] sm:text-5xl">Verify, don’t just trust.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-white/50">Verifiable token facts, project allocations and documented reserve state. Planned allocations are never presented as completed distribution.</p>
    <section className="mt-8 flex flex-col gap-3 rounded-2xl border border-[#e9b949]/15 bg-[#e9b949]/[.035] p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-black tracking-[.18em] text-[#e9b949]">PUBLIC REVIEW STATUS</p><p className="mt-1 text-sm font-black">Reviewed · 12 September 2026</p></div><div className="flex flex-wrap gap-2"><Badge text="MAINNET LIVE"/><Badge text="MINT REVOKED"/><Badge text="FREEZE NONE"/></div></section>
    <section className="mt-8 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Card label="Supply" value="1B MALTY"/><Card label="Decimals" value="6"/><Card label="Mint Authority" value="Revoked"/><Card label="Freeze Authority" value="None"/></section>
    <section className="mt-8 rounded-2xl border border-[#e9b949]/20 bg-[#e9b949]/[.04] p-5"><p className="text-[10px] font-black tracking-[.18em] text-[#e9b949]">OFFICIAL MAINNET MINT</p><p className="mt-2 break-all font-mono text-xs text-white/65">{MINT}</p><a href={`https://explorer.solana.com/address/${MINT}`} target="_blank" rel="noopener noreferrer" className="mt-4 inline-flex rounded-lg bg-[#e9b949] px-3 py-2 text-xs font-black text-black">Verify on Solana Explorer ↗</a></section>
    <section className="mt-12"><p className="text-[10px] font-black tracking-[.22em] text-[#e9b949]">RESERVE ARCHITECTURE</p><h2 className="mt-2 text-2xl font-black">Planned allocation vs. documented state</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/45">At the latest documented reconciliation, each published reserve account held 0 MALTY and no reserve transfer had been executed.</p><div className="mt-6 space-y-2">{reserves.map(([name,planned,wallet])=><div key={name} className="rounded-xl border border-white/[.08] bg-white/[.025] p-4"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-black">{name}</p><p className="text-[10px]"><span className="text-[#e9b949]">{planned}</span><span className="ml-3 text-white/35">Documented: 0 MALTY</span></p></div><p className="mt-2 break-all font-mono text-[10px] text-white/32">{wallet}</p></div>)}</div></section>
    <section className="mt-12"><p className="text-[10px] font-black tracking-[.22em] text-[#e9b949]">PUBLIC HISTORY</p><h2 className="mt-2 text-2xl font-black">Material milestones</h2><div className="mt-5 grid gap-2 sm:grid-cols-2"><Info title="Mainnet foundation" text="1B fixed supply, 6 decimals, no Freeze Authority."/><Info title="Supply authority" text="Mint Authority permanently revoked."/><Info title="Allocation" text="50% Liquidity · 20% Ecosystem · 15% Community · 7.5% Treasury · 7.5% Team."/><Info title="MALTY Gives" text="Policy-first initiative remains Planned; no contribution percentage promised."/></div><a href="/updates" className="mt-5 inline-flex text-sm font-bold text-[#e9b949]">View public changelog →</a></section>
    <section className="mt-12 rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><p className="text-[10px] font-black tracking-[.18em] text-[#e9b949]">STEWARDSHIP DISCLOSURE</p><p className="mt-3 max-w-3xl text-sm leading-6 text-white/45">MALTY is currently stewarded by a project team. The public site does not describe the project as decentralized governance today. Material project changes should be reflected in public documentation and the changelog.</p><a href="/about" className="mt-4 inline-flex text-sm font-bold text-[#e9b949]">Read project stewardship →</a></section>
    <section className="mt-12 flex flex-wrap gap-3"><a href="/docs" className="rounded-xl border border-white/12 px-4 py-2.5 text-sm font-bold">Public documentation</a><a href="/gives" className="rounded-xl border border-white/12 px-4 py-2.5 text-sm font-bold">MALTY Gives</a><a href="/updates" className="rounded-xl border border-white/12 px-4 py-2.5 text-sm font-bold">Project updates</a></section>
    <footer className="mt-14 border-t border-white/[.08] pt-6 text-[10px] leading-5 text-white/28">MALTY is a community-driven digital token on Solana. Transparency documentation does not promise price, returns, liquidity or future value.</footer>
  </div></main>;
}
function Badge({text}:{text:string}){return <span className="rounded-full border border-emerald-400/15 bg-emerald-400/[.05] px-2.5 py-1 text-[9px] font-black text-emerald-300">{text}</span>}
function Card({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/[.08] bg-white/[.025] p-4"><p className="text-[10px] text-white/32">{label}</p><p className="mt-1 text-sm font-black text-[#e9b949]">{value}</p></div>}
function Info({title,text}:{title:string;text:string}){return <div className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><p className="text-sm font-black text-[#e9b949]">{title}</p><p className="mt-2 text-xs leading-5 text-white/42">{text}</p></div>}
